(function(){
if(document.querySelector('[data-view="presets"]')) return;
const css=`.preset-toolbar{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:14px 0}.preset-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.preset-card{border:1px solid var(--line);background:#0c1a29;border-radius:18px;padding:15px;display:flex;flex-direction:column;gap:10px}.preset-card h3{margin:0;font-size:1.05rem}.preset-card p{margin:0;color:var(--muted);font-size:.83rem;line-height:1.45}.preset-card .actions{display:flex;gap:8px;margin-top:auto}.preset-card .actions .btn{flex:1}.preset-exercises{font-size:.78rem;color:#c6d5e4;line-height:1.5}.preset-tag{display:inline-flex;align-items:center;border:1px solid #34536f;border-radius:999px;padding:4px 8px;font-size:.7rem;color:#c8d7e6;margin:0 4px 4px 0}.preset-tag.bodyweight{border-color:#356b55;color:#a7e2c4}.preset-tag.mixed{border-color:#6d4fb0;color:#d5c7ff}.preset-tag.sport{border-color:#8a6a2f;color:#ffe0a0}@media(max-width:900px){.preset-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.preset-toolbar,.preset-grid{grid-template-columns:1fr}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const tabs=document.querySelector('.tabs');const favTab=tabs.querySelector('[data-view="favourites"]');const tab=document.createElement('button');tab.className='tab';tab.dataset.view='presets';tab.textContent='Workout plans';tabs.insertBefore(tab,favTab);tab.addEventListener('click',()=>switchView('presets'));
const fav=document.getElementById('view-favourites');const view=document.createElement('section');view.className='view';view.id='view-presets';view.innerHTML=`<div class="library-wrap"><div class="row spread"><div><h2 style="margin:0">Workout plans</h2><p class="muted" style="margin:5px 0 0">Ready-made sessions for body-part days, bodyweight training, mixed gym workouts and sport-focused mobility.</p></div></div><div class="notice" style="margin-top:14px">Use these as starting points. Load a plan, then use <strong>Edit session</strong> to change exercise order, timing, sets, reps or rest. Sport-focused plans support general mobility and conditioning and should be adapted to ability and professional advice.</div><div class="preset-toolbar"><div class="field"><label>Focus</label><select id="presetFocusFilter"><option value="All">All workout types</option><option>Legs</option><option>Arms</option><option>Chest</option><option>Back</option><option>Abs/Core</option><option>Glutes</option><option>Full Body</option><option>Golf</option><option>Tennis</option><option>Cycling</option></select></div><div class="field"><label>Equipment style</label><select id="presetEquipmentFilter"><option value="All">All equipment styles</option><option value="Bodyweight">Bodyweight only</option><option value="Free weights">Free weights</option><option value="Mixed gym">Mixed gym</option><option value="Mobility">Mobility / sport prep</option></select></div></div><div class="preset-grid" id="presetGrid"></div></div>`;fav.parentNode.insertBefore(view,fav);
const R={sq:'Quads',ha:'Hamstrings',gl:'Glutes',ca:'Calves',kn:'Knees',bi:'Biceps',tr:'Triceps',sh:'Shoulders',wr:'Wrists/Forearms',ch:'Chest/Pecs',la:'Lats',ub:'Upper Back',lb:'Lower Back',co:'Core/Abs',hi:'Hips',an:'Feet/Ankles',fu:'Full Body'};
const typeFor=n=>/stretch/i.test(n)?'Stretch':/mobility|rotation|CAR|ankle dorsiflexion|cat|open book/i.test(n)?'Mobility':/shuffle/i.test(n)?'Cardio':/balance/i.test(n)?'Balance':'Strength';
const ex=(a,i)=>({id:'plan-'+a[0].toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+i,name:a[0],region:R[a[1]]||'Full Body',type:typeFor(a[0]),equipment:a[2]||'body only',description:'Use a controlled range, steady technique and a resistance appropriate to your ability.',media:'',mediaType:'image',duration:a[3]||45,rest:a[4]??20,sets:a[5]||3,reps:a[6]??10,builtin:false});
const P=(id,focus,style,name,desc,items)=>({id,focus,style,name,desc,ex:items.map(ex),sport:['Golf','Tennis','Cycling'].includes(focus)});
const plans=[
P('legs-a','Legs','Bodyweight','Leg Day — Bodyweight A','No-equipment squat, lunge, glute and calf work.',[['Bodyweight Squat','sq'],['Reverse Lunge','sq'],['Single-Leg Glute Bridge','gl'],['Wall Sit','sq','body only',40,20,3,0],['Standing Calf Raise','ca','body only',45,15,3,15],['Single-Leg Balance','an','body only',40,0,2,0]]),
P('legs-b','Legs','Free weights','Leg Day — Free Weights B','Dumbbell squat, hinge and unilateral lower-body training.',[['Goblet Squat','sq','dumbbell',50,30,4,10],['Dumbbell Romanian Deadlift','ha','dumbbell',50,30,4,10],['Dumbbell Split Squat','sq','dumbbell'],['Dumbbell Step-Up','kn','dumbbell'],['Dumbbell Calf Raise','ca','dumbbell',45,20,3,15],['Suitcase Carry','fu','dumbbell',40,0,3,0]]),
P('legs-c','Legs','Mixed gym','Leg Day — Gym Mix C','Machines, free weights and bodyweight for a varied lower-body day.',[['Leg Press','sq','machine',50,35,4,10],['Romanian Deadlift','ha','barbell',50,35,4,8],['Walking Lunge','sq'],['Leg Curl','ha','machine'],['Leg Extension','sq','machine'],['Standing Calf Raise','ca','machine',45,0,3,15]]),
P('arms-a','Arms','Bodyweight','Arm Day — Bodyweight A','Triceps, shoulders and arm-support strength without weights.',[['Close-Grip Push-Up','tr'],['Bench Triceps Dip','tr'],['Pike Push-Up','sh'],['Plank Shoulder Tap','sh'],['Bodyweight Triceps Extension','tr'],['Wrist Mobility Flow','wr','body only',45,0,2,0]]),
P('arms-b','Arms','Free weights','Arm Day — Dumbbells B','Classic biceps, triceps and forearm work.',[['Dumbbell Biceps Curl','bi','dumbbell'],['Hammer Curl','bi','dumbbell'],['Overhead Triceps Extension','tr','dumbbell'],['Dumbbell Skull Crusher','tr','dumbbell'],['Reverse Curl','wr','dumbbell'],['Farmer Carry','fu','dumbbell',45,0,3,0]]),
P('arms-c','Arms','Mixed gym','Arm Day — Gym Mix C','Cable, machine and free-weight arm session.',[['Cable Curl','bi','cable'],['Rope Triceps Pressdown','tr','cable'],['Incline Dumbbell Curl','bi','dumbbell'],['Machine Triceps Extension','tr','machine'],['Cable Reverse Curl','wr','cable'],['Assisted Dip','tr','machine',45,0,3,8]]),
P('chest-a','Chest','Bodyweight','Chest Day — Bodyweight A','Push-up variations plus chest and shoulder mobility.',[['Push-Up','ch','body only',45,25,4,10],['Incline Push-Up','ch'],['Wide Push-Up','ch'],['Slow Eccentric Push-Up','ch','body only',40,25,3,6],['Scapular Push-Up','sh'],['Doorway Pec Stretch','ch','body only',45,0,2,0]]),
P('chest-b','Chest','Free weights','Chest Day — Dumbbells B','Press and fly variations with dumbbells.',[['Dumbbell Chest Press','ch','dumbbell',50,30,4,10],['Incline Dumbbell Press','ch','dumbbell',50,30,4,10],['Dumbbell Fly','ch','dumbbell'],['Dumbbell Pullover','la','dumbbell'],['Push-Up Finisher','ch'],['Doorway Pec Stretch','ch','body only',45,0,2,0]]),
P('chest-c','Chest','Mixed gym','Chest Day — Gym Mix C','Machine, cable, free-weight and bodyweight chest work.',[['Machine Chest Press','ch','machine',50,30,4,10],['Incline Dumbbell Press','ch','dumbbell'],['Cable Fly','ch','cable'],['Push-Up','ch'],['Pec Deck','ch','machine'],['Cross-Body Shoulder Stretch','sh','body only',40,0,2,0]]),
P('back-a','Back','Bodyweight','Back Day — Bodyweight A','Posterior-chain and shoulder-blade control with no weights.',[['Bird-Dog','lb'],['Prone Y Raise','ub'],['Prone W Raise','ub'],['Reverse Snow Angel','ub'],['Hip Hinge','lb'],['Cat–Cow','ub','body only',45,0,2,0]]),
P('back-b','Back','Free weights','Back Day — Free Weights B','Dumbbell and barbell pulling with posterior-chain work.',[['One-Arm Dumbbell Row','la','dumbbell',50,30,4,10],['Romanian Deadlift','ha','barbell',50,30,4,8],['Dumbbell Reverse Fly','ub','dumbbell'],['Chest-Supported Dumbbell Row','ub','dumbbell'],['Dumbbell Pullover','la','dumbbell'],['Suitcase Carry','fu','dumbbell',45,0,3,0]]),
P('back-c','Back','Mixed gym','Back Day — Gym Mix C','Pulldown, cable, machine and free-weight back session.',[['Lat Pulldown','la','cable',50,30,4,10],['Seated Cable Row','ub','cable',50,30,4,10],['Machine Row','ub','machine'],['One-Arm Dumbbell Row','la','dumbbell'],['Face Pull','ub','cable'],['90° Lat Stretch','la','body only',45,0,2,0]]),
P('core-a','Abs/Core','Bodyweight','Abs & Core — Bodyweight A','Anti-extension, side-core and controlled trunk work.',[['Dead Bug','co'],['Front Plank','co','body only',40,20,3,0],['Side Plank','co','body only',35,20,3,0],['Bird-Dog','lb'],['Slow Mountain Climber','co'],['Hollow Hold Regression','co','body only',35,0,3,0]]),
P('core-b','Abs/Core','Free weights','Abs & Core — Loaded B','Dumbbell and carry-based trunk training.',[['Suitcase Carry','co','dumbbell',45,25,4,0],['Goblet March','co','dumbbell'],['Half-Kneeling Dumbbell Hold','co','dumbbell',40,20,3,0],['Dumbbell Dead Bug','co','dumbbell'],['Farmer Carry','fu','dumbbell',45,20,3,0],['Weighted Glute Bridge','gl','dumbbell',45,0,3,12]]),
P('core-c','Abs/Core','Mixed gym','Abs & Core — Athletic C','Cable, bodyweight and loaded carries for variety.',[['Pallof Press','co','cable'],['Cable Chop','co','cable'],['Front Plank','co','body only',40,20,3,0],['Hanging Knee Raise','co','bar'],['Farmer Carry','fu','dumbbell',45,20,3,0],['Side Plank','co','body only',35,0,3,0]]),
P('glutes-a','Glutes','Bodyweight','Glute Day — Bodyweight A','Bridges, abduction and single-leg glute work.',[['Glute Bridge','gl','body only',45,20,4,12],['Single-Leg Glute Bridge','gl'],['Clamshell','gl','body only',45,20,3,15],['Quadruped Hip Extension','gl'],['Lateral Lunge','gl'],['Kneeling Hip-Flexor Stretch','hi','body only',45,0,2,0]]),
P('glutes-b','Glutes','Free weights','Glute Day — Free Weights B','Hip thrust, hinge and split-squat emphasis.',[['Hip Thrust','gl','barbell',50,30,4,10],['Romanian Deadlift','ha','barbell',50,30,4,8],['Dumbbell Bulgarian Split Squat','gl','dumbbell'],['Dumbbell Step-Up','gl','dumbbell'],['Dumbbell Frog Pump','gl','dumbbell',40,20,3,15],['Suitcase Carry','fu','dumbbell',40,0,3,0]]),
P('glutes-c','Glutes','Mixed gym','Glute Day — Gym Mix C','Machine, cable, free-weight and band glute work.',[['Hip Thrust','gl','barbell',50,30,4,10],['Cable Hip Abduction','gl','cable'],['Leg Press — High Foot','gl','machine',50,30,3,10],['Walking Lunge','gl'],['Glute Kickback','gl','cable'],['Band Lateral Walk','gl','bands',45,0,3,12]]),
P('full-a','Full Body','Bodyweight','Full Body — Bodyweight Only','No-equipment whole-body training for home or travel.',[['Bodyweight Squat','sq'],['Push-Up','ch'],['Reverse Lunge','sq'],['Bird-Dog','lb'],['Glute Bridge','gl'],['Front Plank','co','body only',40,20,3,0],['Calf Raise','ca','body only',40,0,3,15]]),
P('full-b','Full Body','Mixed gym','Full Body — Gym Mix','Balanced machines, free weights and bodyweight.',[['Goblet Squat','sq','dumbbell',50,30,3,10],['Machine Chest Press','ch','machine',50,30,3,10],['Lat Pulldown','la','cable',50,30,3,10],['Romanian Deadlift','ha','barbell',50,30,3,8],['Seated Cable Row','ub','cable'],['Walking Lunge','gl'],['Farmer Carry','fu','dumbbell',45,0,3,0]]),
P('golf-a','Golf','Mobility','Golf — Mobility & Rotation A','Hip, thoracic, shoulder and rotational mobility for golf.',[['Cat–Cow','ub','body only',45,15,2,0],['Open Book Rotation','ub','body only',45,15,2,8],['Hip 90/90 Rotation','hi','body only',45,15,2,8],['Kneeling Hip-Flexor Stretch','hi','body only',45,15,2,0],['Doorway Pec Stretch','ch','body only',40,15,2,0],['Pallof Press','co','bands',45,15,2,10],['Bodyweight Hip Hinge','lb','body only',45,0,2,10]]),
P('golf-b','Golf','Mobility','Golf — Strength & Control B','Rotational control, glutes and trunk stability.',[['Split Squat','sq'],['Single-Leg Romanian Deadlift','ha','dumbbell'],['Cable Chop','co','cable'],['Pallof Press','co','cable'],['One-Arm Row','la','dumbbell'],['Glute Bridge','gl','body only',45,0,3,12]]),
P('tennis-a','Tennis','Mobility','Tennis — Mobility & Court Prep A','Shoulder, trunk, hip and ankle mobility with light movement prep.',[['Shoulder CARs','sh','body only',45,15,2,0],['Open Book Rotation','ub','body only',45,15,2,8],['Lateral Lunge','hi','body only',45,15,2,8],['Ankle Dorsiflexion','an','body only',45,15,2,10],['Band External Rotation','sh','bands',45,15,2,12],['Side Plank','co','body only',35,15,2,0],['Easy Lateral Shuffle','fu','body only',45,0,2,0]]),
P('tennis-b','Tennis','Mobility','Tennis — Strength & Change-of-Direction B','Leg, shoulder and trunk strength for court-sport demands.',[['Split Squat','sq','dumbbell'],['Lateral Lunge','gl'],['One-Arm Cable Row','la','cable'],['Band External Rotation','sh','bands'],['Pallof Press','co','cable'],['Calf Raise','ca','body only',45,0,3,15]]),
P('cycling-a','Cycling','Mobility','Cycling — Mobility Reset A','Hip, quad, calf, hamstring and upper-back mobility.',[['Kneeling Hip-Flexor Stretch','hi','body only',45,15,2,0],['Standing Quad Stretch','sq','body only',45,15,2,0],['Seated Hamstring Stretch','ha','body only',45,15,2,0],['Wall Calf Stretch','ca','body only',45,15,2,0],['Cat–Cow','ub','body only',45,15,2,0],['Doorway Pec Stretch','ch','body only',40,15,2,0],['Glute Bridge','gl','body only',45,0,2,12]]),
P('cycling-b','Cycling','Mobility','Cycling — Strength & Stability B','Lower-body and trunk strength to complement cycling.',[['Goblet Squat','sq','dumbbell',50,25,3,10],['Romanian Deadlift','ha','dumbbell',50,25,3,10],['Step-Up','sq'],['Single-Leg Glute Bridge','gl'],['Standing Calf Raise','ca','body only',45,20,3,15],['Dead Bug','co','body only',45,0,3,10]])
];
function loadPlan(p,edit){state.session=normaliseSession(JSON.parse(JSON.stringify(p.ex)));resetRunner();switchView('session');toast(p.name+' loaded');if(edit)setTimeout(()=>{renderEditRows();openModal('editModal')},120)}
function render(){const grid=document.getElementById('presetGrid'),f=document.getElementById('presetFocusFilter').value,s=document.getElementById('presetEquipmentFilter').value;grid.innerHTML='';const list=plans.filter(p=>(f==='All'||p.focus===f)&&(s==='All'||p.style===s));if(!list.length){grid.innerHTML='<div class="empty" style="grid-column:1/-1">No plans match those filters.</div>';return}list.forEach(p=>{const d=document.createElement('div');d.className='preset-card';const tag=p.sport?'sport':p.style==='Bodyweight'?'bodyweight':p.style==='Mixed gym'?'mixed':'';let total=0;p.ex.forEach((x,i)=>{total+=x.duration+(i<p.ex.length-1?x.rest:0)});d.innerHTML=`<div><span class="preset-tag ${tag}">${p.focus}</span><span class="preset-tag ${tag}">${p.style}</span></div><h3>${p.name}</h3><p>${p.desc}</p><div class="preset-exercises"><strong>${p.ex.length} exercises • ${fmt(total)}</strong><br>${p.ex.map(x=>x.name).join(' • ')}</div><div class="actions"><button class="btn green load">Load plan</button><button class="btn edit">Load & edit</button></div>`;d.querySelector('.load').onclick=()=>loadPlan(p,false);d.querySelector('.edit').onclick=()=>loadPlan(p,true);grid.appendChild(d)})}
document.getElementById('presetFocusFilter').onchange=render;document.getElementById('presetEquipmentFilter').onchange=render;render();
})();